#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
# Edited by Mark Phillips, in Nano 5.3
# https://gist.github.com/2c5cb4b4b063d4c63004bbda18ec944a
# wget -O - https://bit.ly/3jrzVGM 
# wget -o ~/.SpaceVim.d/init.toml https://bit.ly/3jrzVGM
#=============================================================================

[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    
    # statusline_separator = "arrow"
    # statusline_iseparator = "arrow"
    # statusline_unicode_symbols = true
   
    buffer_index_type = 4
    enable_cursorcolumn = true
    enable_os_fileformat_icon = true
    enable_tabline_filetype_icon = true
    enable_tabline_ft_icon = true
    enable_statusline_mode = true
    enable_statusline_bfpath = true
    enable_statusline_tag = true
    home_files_number = 20
    #enable_vimfiler_gitstatus = true
    enable_vimfiler_filetypeicon = true
    sidebar_width = 50

    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'branch',
       'version control info',
       'syntax checking',
       'search status'
    ]

    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time',
       'battery status'
    ]

    # 'whitespace' line number with trailing space at the end

    enable_googlesuggest = 1
    github_username = "netyaroze"
    
    #guifont = "GohuFont:h11"
    #guifont = "Iosevka Nerd Font:h11"

    lint_on_the_fly = true
    lint_on_save = true

    # No Relative Numbers
    relativenumber=false


[[layers]]
name = 'core'
  filetree_show_hidden = false

[[layers]]
name = "core#statusline"

[[layers]]
name = "statusline"

[[layers]]
name = "shell"
  default_position = "top"
  default_height = 40
  format_on_save = true

[[layers]]
name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_delay = 100
  auto_completion_complete_with_key_sequence = "nil"
  auto_completion_complete_with_key_sequence_delay = 0.1
  autocomplete_method = "deoplete"
  autocomplete_parens = true

[[layers]]
name = "incsearch"

[[layers]]
name = 'VersionControl'

[[layers]]
name = "git"
git-plugin = "fugitive"
# git-plugin = "gita" # broken in statusline

[[layers]]
name = "github"

[[layers]]
name = 'fzf'

[[layers]]
name = "sudo"

[[layers]]
name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
name = "ui"
  enable_scrollbar = true

[[layers]]
name = "lang#javascript"
  format_on_save = true

[[layers]]
name = "lang#typescript"
  auto_fix = true
  enable_flow_syntax = true
  format_on_save = true

[[layers]]
name = "html"

[[layers]]
name = 'lang#asciidoc'
 
[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#json'
 
[[layers]]
name = 'lang#latex'
 
[[layers]]
name = 'lang#markdown'
# enabled_formater 

[[layers]]
name = 'lang#sh'
 
[[layers]]
name = 'lang#vim'
 
[[layers]]
name = 'lang#extra'
 
[[layers]]
name = "language-server-protocol"

[[custom_plugins]]
repo = "lilydjwg/colorizer"
  on_cmd = ["ColorHighlight", "ColorToggle"]
  merged = false

[[custom_plugins]]
repo = "beautify-web/js-beautify"
  merged = false

[[custom_plugins]]
repo = "mboughaba/i3config.vim"
  merged = false

[[custom_plugins]]
repo="lilydjwg/colorizer"
  merged=false

[[custom_plugins]]
repo = "dbeniamine/todo.txt-vim"
  on_cmd = ["todo.txt"]
  merged = false

#[[custom_plugins]]
#repo = "SpaceVim/org-mode"
#  merged = false

#[[custom_plugins]]
#  repo = "tpope/vim-speeddating"
#  merged = false
